{% set version = "1.0.5" %}
{% set name = "iml" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://www.cs.uwaterloo.ca/~astorjoh/{{ name }}-{{ version }}.tar.bz2
  sha256: 1dad666850895a5709b00b97422e2273f293cfadea7697a9f90b90953e847c2a

build:
  number: 1001
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - libtool
    - {{ compiler('c') }}
  host:
    - gmp
    - openblas
    - blas 1.1 {{ variant }}
  run:
    - gmp
    - openblas
    - blas 1.1 {{ variant }}

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://cs.uwaterloo.ca/~astorjoh/iml.html
  license: GPLv2
  license_file: COPYING
  summary: |
    IML is a free library of C source code which implements algorithms for computing
    exact solutions to dense systems of linear equations over the integers.

extra:
  recipe-maintainers:
    - isuruf
