travis:
  secure:
    BINSTAR_TOKEN: hn7fCwsmt7dSOY0x1SudXudIn2nHWRmaCxsQ5L4xk4+PkbfQOlT8K+CDk7oVkF7j5mg9AdieqvV1BCQHYBt/xcA80P2AVKMlyUnKcTWthUu1GouUnoe9j7GdCHKn1dV0owvNOOnbUpjH+cjFAbvH6uVI/1hhnf2mosqxL0KWrxSkwwn37bsHFdATfvs4iKxUh971wE78hnx517kpGtIKEHIEY48B5Q1Ow2mhCLqSGhOwlL/uFj8za3ucDxHR6OHewoUkerridT+ywEkX+IYrNjxB3Zi0kU4V/r/1jqrwSL8OnF3aS5z8qUWMkTDIg/n3RSXLrGoByAJ8CIfWsCQoRJ1On3qr5BLAQRRw++5PVgzIP1OCDn8wcvtkUus179EsC04p25wbs2Dawo8/MH+iv0jEZ4MQ4Dy7DcBJS2CeUYa/tMjHKwB5cLmxcmjidY7rnbQVrbvzzaI2dA442BEALjLjr3H4ywuT/XXGFuIeFOvEtr6TZPRFCS7Ws5UOy6dMhDzWdHSdj8TaKS7fJAPhZaH7rhC2RrR/H1z1LZy05ymXYZlCVuAuKFhg3CGQBRp1CZ6di+WsFGGZ04equ839Lcdt1jMjQBSGeGGjKFDz1RD1BF5UkIOGkgA1ractg9WgQhyzLXmZ5aegg9ZicfaU+kjge8pItQ3jhjnW1ihzgmU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
